
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524421

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

zeroconf:

lovelace:
  resource_mode: yaml
  resources:
    - url: /hacsfiles/Bubble-Card/bubble-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/modern-circular-gauge/modern-circular-gauge.js
      type: module
    - url: /hacsfiles/slider-button-card/slider-button-card.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
  dashboards:
    garage-hvac:
      mode: yaml
      filename: dashboards/garage_hvac.yaml
      title: Garage HVAC
      icon: mdi:garage-variant
      show_in_sidebar: true

homeassistant:
  packages: !include_dir_named packages
